language: c
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install autotools-dev automake autoconf libtool gtk-doc-tools gperf
script: ./autogen.sh && ./configure --enable-gtk-doc && make V=1 && make distcheck
notifications:
  irc:
    channels:
      - "irc.freenode.org#gentoo-udev"
    on_success: change
    on_failure: always
